export {
  AVATAR_MIN_ZOOM,
  DEFAULT_AVATAR_COLOR,
  DEFAULT_AVATAR_CROP,
  DEFAULT_PRESET_AVATAR_CROP,
  PALETTE,
  avatarCropForImage,
  avatarCropGeometry,
  avatarDefaultCropForSrc,
  avatarPresetBySrc,
  avatarPresetGroupForSrc,
  avatarPresetGroupTabs,
  avatarPresetGroups,
  avatarPresets,
  avatarThumbForSrc,
  canonicalAvatarSrc,
  hasAvatarIdentityFields,
  identityDisplayText,
  isEmojiAvatar,
  isLegacyPresetAvatarSrc,
  isNeutralAvatarCrop,
  isVideoAvatar,
  emojiAvatarGlyph,
  emojiAvatarToken,
  memberAccentColor,
  normalizeAvatarCrop,
  normalizeAvatarDescriptor,
  normalizeAvatarImage,
  resolveAvatar,
  resolveAvatarForContact,
} from "@mia/shared/avatar";

export type { AvatarContactInput, AvatarDescriptor } from "@mia/shared/avatar";
