export const mobileTabBarChrome = {
  floating: true,
  reservesLayoutSpace: false,
  horizontalMargin: 14,
  topGap: 8,
  bottomGap: 8,
  cardRadius: 24,
  cardBackgroundColor: "rgba(255,255,255,0.93)",
  frostedVeilColor: "rgba(255,255,255,0.34)",
  innerHighlightColor: "rgba(255,255,255,0.66)",
  cardBorderColor: "rgba(255,255,255,0.9)",
  cardBorderWidth: 1,
  shadowOpacity: 0.16,
  shadowRadius: 24,
  elevation: 10,
  overlay: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
  },
  reservedLayoutStyle: {
    position: "absolute",
    height: 0,
    backgroundColor: "transparent",
    borderTopWidth: 0,
    elevation: 0,
  },
} as const;
